"""initial_schema_v1

Revision ID: 90a4678bb2ca
Revises: 
Create Date: 2026-01-24 18:20:41.458807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90a4678bb2ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_coupons_code', table_name='coupons')
    op.drop_index('idx_coupons_valid_until', table_name='coupons')
    op.drop_table('coupons')
    op.drop_index('idx_loyalty_points_expires_at', table_name='loyalty_points')
    op.drop_index('idx_loyalty_points_user_id', table_name='loyalty_points')
    op.drop_table('loyalty_points')
    op.drop_index('idx_coupon_usage_coupon_id', table_name='coupon_usage')
    op.drop_index('idx_coupon_usage_user_id', table_name='coupon_usage')
    op.drop_table('coupon_usage')
    op.drop_index('idx_payments_order_id', table_name='payments')
    op.drop_index('idx_payments_transaction_id', table_name='payments')
    op.drop_table('payments')
    op.drop_table('carts')
    op.drop_index('idx_inventory_logs_admin_id', table_name='inventory_logs')
    op.drop_index('idx_inventory_logs_order_id', table_name='inventory_logs')
    op.drop_index('idx_inventory_logs_product_id', table_name='inventory_logs')
    op.drop_table('inventory_logs')
    op.drop_index('idx_product_views_product_id', table_name='product_views')
    op.drop_index('idx_product_views_user_id', table_name='product_views')
    op.drop_index('idx_product_views_viewed_at', table_name='product_views')
    op.drop_table('product_views')
    op.drop_index('idx_orders_created_at', table_name='orders')
    op.drop_index('idx_orders_order_number', table_name='orders')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_tracking_number', table_name='orders')
    op.drop_index('idx_orders_user_id', table_name='orders')
    op.drop_table('orders')
    op.drop_table('product_category_association')
    op.drop_table('product_bundles')
    op.drop_index('idx_return_requests_order_id', table_name='return_requests')
    op.drop_index('idx_return_requests_status', table_name='return_requests')
    op.drop_table('return_requests')
    op.drop_index('idx_product_variations_product_id', table_name='product_variations')
    op.drop_table('product_variations')
    op.drop_index('idx_abandoned_carts_abandoned_at', table_name='abandoned_carts')
    op.drop_index('idx_abandoned_carts_user_id', table_name='abandoned_carts')
    op.drop_table('abandoned_carts')
    op.drop_index('idx_products_active_featured', table_name='products')
    op.drop_index('idx_products_name', table_name='products')
    op.drop_index('idx_products_price', table_name='products')
    op.drop_index('idx_products_sku', table_name='products')
    op.drop_index('idx_products_slug', table_name='products')
    op.drop_index('idx_products_tags', table_name='products', postgresql_using='gin')
    op.drop_index('idx_products_view_count', table_name='products')
    op.drop_table('products')
    op.drop_index('idx_addresses_user_id', table_name='addresses')
    op.drop_table('addresses')
    op.drop_table('shipping_zones')
    op.drop_table('bundle_products')
    op.drop_index('ix_order_status_history_order_id', table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index('idx_cart_items_product_id', table_name='cart_items')
    op.drop_index('idx_cart_items_user_id', table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_table('categories')
    op.drop_index('idx_notifications_is_read', table_name='notifications')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_loyalty_tier', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_price_history_changed_at', table_name='price_history')
    op.drop_index('idx_price_history_product_id', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('idx_reviews_product_id', table_name='reviews')
    op.drop_index('idx_reviews_user_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('idx_product_images_product_id', table_name='product_images')
    op.drop_table('product_images')
    op.drop_index('idx_tax_rates_location', table_name='tax_rates')
    op.drop_table('tax_rates')
    op.drop_index('idx_order_items_order_id', table_name='order_items')
    op.drop_index('idx_order_items_product_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('idx_wishlists_product_id', table_name='wishlists')
    op.drop_index('idx_wishlists_user_id', table_name='wishlists')
    op.drop_table('wishlists')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlists',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('price_at_addition', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('notify_on_price_drop', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='wishlists_product_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='wishlists_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='wishlists_pkey'),
    sa.UniqueConstraint('user_id', 'product_id', name='wishlists_user_id_product_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_wishlists_user_id', 'wishlists', ['user_id'], unique=False)
    op.create_index('idx_wishlists_product_id', 'wishlists', ['product_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('variation_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.CheckConstraint('price >= 0::numeric', name='order_items_price_check'),
    sa.CheckConstraint('quantity > 0', name='order_items_quantity_check'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_items_order_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='order_items_product_id_fkey'),
    sa.ForeignKeyConstraint(['variation_id'], ['product_variations.id'], name='order_items_variation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='order_items_pkey')
    )
    op.create_index('idx_order_items_product_id', 'order_items', ['product_id'], unique=False)
    op.create_index('idx_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_table('tax_rates',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('country', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('rate', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tax_rates_pkey')
    )
    op.create_index('idx_tax_rates_location', 'tax_rates', ['country', 'state', 'city'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('alt_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_images_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='product_images_pkey')
    )
    op.create_index('idx_product_images_product_id', 'product_images', ['product_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('is_verified_purchase', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_approved', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('helpful_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='reviews_rating_check'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='reviews_product_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reviews_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='reviews_pkey')
    )
    op.create_index('idx_reviews_user_id', 'reviews', ['user_id'], unique=False)
    op.create_index('idx_reviews_product_id', 'reviews', ['product_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('original_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('changed_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name='price_history_changed_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='price_history_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='price_history_pkey')
    )
    op.create_index('idx_price_history_product_id', 'price_history', ['product_id'], unique=False)
    op.create_index('idx_price_history_changed_at', 'price_history', ['changed_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=True),
    sa.Column('loyalty_tier', sa.VARCHAR(length=50), server_default=sa.text("'bronze'::character varying"), autoincrement=False, nullable=True),
    sa.Column('loyalty_points', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('preferred_currency', sa.VARCHAR(length=3), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name='users_username_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_loyalty_tier', 'users', ['loyalty_tier'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('categories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='categories_pkey'),
    sa.UniqueConstraint('name', name='categories_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('cart_items',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('variation_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('cart_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_reserved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('reserved_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint('quantity > 0', name='cart_items_quantity_check'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name='cart_items_cart_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='cart_items_product_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='cart_items_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variation_id'], ['product_variations.id'], name='cart_items_variation_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cart_items_pkey')
    )
    op.create_index('idx_cart_items_user_id', 'cart_items', ['user_id'], unique=False)
    op.create_index('idx_cart_items_product_id', 'cart_items', ['product_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('from_status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('to_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name='order_status_history_changed_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_status_history_order_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='order_status_history_pkey')
    )
    op.create_index('ix_order_status_history_order_id', 'order_status_history', ['order_id'], unique=False)
    op.create_table('bundle_products',
    sa.Column('bundle_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['product_bundles.id'], name='bundle_products_bundle_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='bundle_products_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bundle_id', 'product_id', name='bundle_products_pkey')
    )
    op.create_table('shipping_zones',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('countries', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('states', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('postal_codes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('base_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('per_item_rate', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('free_shipping_threshold', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('estimated_days_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_days_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='shipping_zones_pkey')
    )
    op.create_table('addresses',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('addresses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('address_line_1', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('address_line_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='addresses_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='addresses_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_addresses_user_id', 'addresses', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('products_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('original_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=2, scale=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('review_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('primary_image', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('short_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('sale_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('average_rating', sa.NUMERIC(precision=3, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_new', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_bestseller', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('meta_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('meta_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.CheckConstraint('original_price >= 0::numeric OR original_price IS NULL', name='products_original_price_check'),
    sa.CheckConstraint('price >= 0::numeric', name='products_price_check'),
    sa.CheckConstraint('rating >= 0::numeric AND rating <= 5::numeric', name='products_rating_check'),
    sa.CheckConstraint('review_count >= 0', name='products_review_count_check'),
    sa.CheckConstraint('stock >= 0', name='products_stock_check'),
    sa.PrimaryKeyConstraint('id', name='products_pkey'),
    sa.UniqueConstraint('sku', name='products_sku_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_products_view_count', 'products', ['view_count'], unique=False)
    op.create_index('idx_products_tags', 'products', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_products_slug', 'products', ['slug'], unique=False)
    op.create_index('idx_products_sku', 'products', ['sku'], unique=False)
    op.create_index('idx_products_price', 'products', ['price'], unique=False)
    op.create_index('idx_products_name', 'products', ['name'], unique=False)
    op.create_index('idx_products_active_featured', 'products', ['is_active', 'is_featured'], unique=False)
    op.create_table('abandoned_carts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('cart_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('total_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('abandoned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('recovery_email_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('recovered', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('recovered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='abandoned_carts_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='abandoned_carts_pkey')
    )
    op.create_index('idx_abandoned_carts_user_id', 'abandoned_carts', ['user_id'], unique=False)
    op.create_index('idx_abandoned_carts_abandoned_at', 'abandoned_carts', ['abandoned_at'], unique=False)
    op.create_table('product_variations',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('price_adjustment', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('stock', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('sku', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.CheckConstraint('price_adjustment IS NOT NULL', name='product_variations_price_adjustment_check'),
    sa.CheckConstraint('stock >= 0', name='product_variations_stock_check'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_variations_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='product_variations_pkey'),
    sa.UniqueConstraint('sku', name='product_variations_sku_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_product_variations_product_id', 'product_variations', ['product_id'], unique=False)
    op.create_table('return_requests',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('refund_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying::text, 'approved'::character varying::text, 'rejected'::character varying::text, 'completed'::character varying::text])", name='return_requests_status_check'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name='return_requests_approved_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='return_requests_order_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='return_requests_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='return_requests_pkey')
    )
    op.create_index('idx_return_requests_status', 'return_requests', ['status'], unique=False)
    op.create_index('idx_return_requests_order_id', 'return_requests', ['order_id'], unique=False)
    op.create_table('product_bundles',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discount_percentage', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='product_bundles_pkey')
    )
    op.create_table('product_category_association',
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='product_category_association_category_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_category_association_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'category_id', name='product_category_association_pkey')
    )
    op.create_table('orders',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('orders_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('shipping_cost', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('tax_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('tracking_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('carrier', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('estimated_delivery', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('coupon_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('loyalty_points_earned', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('loyalty_points_used', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.CheckConstraint('shipping_cost >= 0::numeric', name='orders_shipping_cost_check'),
    sa.CheckConstraint('tax_amount >= 0::numeric', name='orders_tax_amount_check'),
    sa.CheckConstraint('total_amount >= 0::numeric', name='orders_total_amount_check'),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], name='orders_address_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='orders_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='orders_pkey'),
    sa.UniqueConstraint('order_number', name='orders_order_number_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_index('idx_orders_tracking_number', 'orders', ['tracking_number'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_index('idx_orders_order_number', 'orders', ['order_number'], unique=False)
    op.create_index('idx_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_table('product_views',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('viewed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('referrer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_views_product_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='product_views_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='product_views_pkey')
    )
    op.create_index('idx_product_views_viewed_at', 'product_views', ['viewed_at'], unique=False)
    op.create_index('idx_product_views_user_id', 'product_views', ['user_id'], unique=False)
    op.create_index('idx_product_views_product_id', 'product_views', ['product_id'], unique=False)
    op.create_table('inventory_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('change_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('new_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('admin_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('new_stock >= 0 OR new_stock IS NULL', name='inventory_logs_new_stock_check'),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name='inventory_logs_admin_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='inventory_logs_order_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='inventory_logs_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='inventory_logs_pkey')
    )
    op.create_index('idx_inventory_logs_product_id', 'inventory_logs', ['product_id'], unique=False)
    op.create_index('idx_inventory_logs_order_id', 'inventory_logs', ['order_id'], unique=False)
    op.create_index('idx_inventory_logs_admin_id', 'inventory_logs', ['admin_id'], unique=False)
    op.create_table('carts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('tax_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('discount_amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('total', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('promo_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='carts_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='carts_pkey')
    )
    op.create_table('payments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.CheckConstraint('amount >= 0::numeric', name='payments_amount_check'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='payments_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey'),
    sa.UniqueConstraint('transaction_id', name='payments_transaction_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_payments_transaction_id', 'payments', ['transaction_id'], unique=False)
    op.create_index('idx_payments_order_id', 'payments', ['order_id'], unique=False)
    op.create_table('coupon_usage',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('coupon_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('discount_applied', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name='coupon_usage_coupon_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='coupon_usage_order_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='coupon_usage_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='coupon_usage_pkey')
    )
    op.create_index('idx_coupon_usage_user_id', 'coupon_usage', ['user_id'], unique=False)
    op.create_index('idx_coupon_usage_coupon_id', 'coupon_usage', ['coupon_id'], unique=False)
    op.create_table('loyalty_points',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='loyalty_points_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='loyalty_points_pkey')
    )
    op.create_index('idx_loyalty_points_user_id', 'loyalty_points', ['user_id'], unique=False)
    op.create_index('idx_loyalty_points_expires_at', 'loyalty_points', ['expires_at'], unique=False)
    op.create_table('coupons',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discount_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('discount_value', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('min_purchase_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('max_discount_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('usage_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('usage_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('valid_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('valid_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('applicable_categories', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('applicable_products', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("discount_type::text = ANY (ARRAY['percentage'::character varying::text, 'fixed'::character varying::text, 'free_shipping'::character varying::text])", name='coupons_discount_type_check'),
    sa.PrimaryKeyConstraint('id', name='coupons_pkey'),
    sa.UniqueConstraint('code', name='coupons_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_coupons_valid_until', 'coupons', ['valid_until'], unique=False)
    op.create_index('idx_coupons_code', 'coupons', ['code'], unique=False)
    # ### end Alembic commands ###
